---
- name: Playbook to install Apache
  hosts: web
  become: true

  tasks: 
    - name: Install httpd
      yum: 
        name: httpd
        state: present
      
    - name: Start the Services   
      service: 
        name: httpd
        state: started
        enabled: yes
    - name: Set website Content  
      copy: 
        dest: /var/www/html/index.html
        content: | 
                    Welcome:)

